spring:
  application:
    name: boilerplate
  main:
    web-application-type: servlet
  web:
    resources:
      add-mappings: false
  autoconfigure:
    time-zone: America/Sao_Paulo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: ${DB_NAME}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    mapper:
      default-view-inclusion: true

server:
  port: ${API_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.jdbc.core: DEBUG        # Loga as queries SQL feitas pelo JdbcTemplate
    org.springframework.jdbc.datasource: DEBUG  # Loga operações com o DataSource

tokens:
  secret: ${JWT_SECRET}
  host: ${HOST}
  uploadDir: ${UPLOAD_DIR}
  infinitePayEndpoint: ${INFINITE_PAY_ENDPOINT}
  infinitePayHandle: ${INFINITE_PAY_HANDLE}
  infinitePayRedirectUrl: ${INFINITE_PAY_REDIRECT_URL}
  infinitePayWebhookUrl: ${INFINITE_PAY_WEBHOOK_URL}